on:
  push:
    branches: main

jobs:
  set-up-db:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyr
            any::duckdb
            any::arrow
            any::here
            any::DBI
            any::stringr
            any::purrr

      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up directories
        run: Rscript -e 'source("scripts/00-forestTIME_setup.R")'        
      - name: Download data
        run: Rscript -e 'source("scripts/01a-download_files_from_DataMart.R")'
      - name: Create db
        run: Rscript -e 'source("scripts/01b-create_database.R")'
      - name: Commit results
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add data/db/foresttime-to-share.duckdb
            git commit -m 'Data updated' 
            git push origin 